topic: apmt.terminalOperations.apistore.test  #Overwrite with correct topic
kafkabootstrapservers: pp-we-1-dedicated-kafka-bootstrap.io:443
kafkaUsername: pp.push-notify.v1
kafkaPassword: password
kafkaProducerUserName: pp.push-notify.v1
kafkaProducerPassword: password
kafkaConsumerGroup2: operations.apistore
kafkaSchemaRegistryUrl: https://pp-we-1-dedicated-kafka-sr.io/
kafkaConsumerSchemaRegistryUrl: https://pp-we-1-dedicated-kafka-sr.io/
kafkaConsumerSchemaRegistryApiKey: changeit
kafkaConsumerSchemaRegistryApiSecret: changeit
ssl-keystore-location: /Users/vicky/Documents/CDH-Secrets/apmt-keystore 1.jks
ssl-keystore-password: test
ssl-truststore-location: /Users/vicky/Documents/CDH-Secrets/apmt-truststore 1.jks
ssl-truststore-password: test
kafkaProducerLoginModule: "org.apache.kafka.common.security.scram.ScramLoginModule"
kafkaProducerSecurityProtocol: "SASL_SSL"
kafkaProducerSaSLMechanism: "SCRAM-SHA-512"
SPRING_CONFIG_IMPORT: configserver:http://config-server-v1
kafkaSaslJaasConfig: org.apache.kafka.common.security.scram.ScramLoginModule required  username="pp.push-notify.v1" password="password";
keystorePassword: test
truststorePassword: test
kafkaSaslMechanism: SCRAM-SHA-512



cdc:
  mysql:
    hostname: apistore.database.windows.net
    port: 1433
    username: api-admin
    password: password
    database: APIGEE
    table: watchlistTopic

  kafka:
    bootstrap-servers: ${kafkabootstrapservers}
    topic: apmt.terminalOperations.apistore.test
    client-id: container-event-notification
    schema-registry-url: ${kafkaSchemaRegistryUrl}
    username: ${kafkaProducerUserName}
    password: ${kafkaProducerPassword}
    login-module: ${kafkaProducerLoginModule}
    sasl-mechanism: ${kafkaProducerSaSLMechanism}
    security-protocol: ${kafkaProducerSecurityProtocol}
    consumer-group: ${kafkaConsumerGroup2}

    ssl-keystore-location: /Users/vicky/Documents/CDH-Secrets/apmt-keystore\ 1.jks
    ssl-keystore-password: test
    ssl-truststore-location: /Users/vicky/Documents/CDH-Secrets/apmt-truststore\ 1.jks
    ssl-truststore-password: test
